name: build rust images

on:
  push:
    branches:
      - 'main'

jobs:

  build-images:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.ZIMG_DOCKERHUB_USERNAME }}
          password: ${{ secrets.ZIMG_DOCKERHUB_PASSWORD }}
      -
        name: rust-1.56.1
        uses: docker/build-push-action@v2
        with:
          context: rust/1.56.1
          pull: true
          push: true
          tags: zimg/rust:1.56.1,zimg/rust:1.56,zimg/rust:stable

      -
        name: rust-1.58.1
        uses: docker/build-push-action@v2
        with:
          context: rust/1.58.1
          pull: true
          push: true
          tags: zimg/rust:1.58.1,zimg/rust:1.58,zimg/rust:edge
