name: build rust images

on:
  push:
    branches:
      - 'main'

jobs:
  build-images:
    strategy:
      matrix:
        include:
          - os: ubuntu-20.04
            rust_image_name: rust
            suffix: ''
          - os: amd64/ubuntu-20.04
            rust_image_name: arm64v8/rust
            suffix: -amd64

    name: build-images (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.ZIMG_DOCKERHUB_USERNAME }}
          password: ${{ secrets.ZIMG_DOCKERHUB_PASSWORD }}
      -
        name: rust-1.56.1
        uses: docker/build-push-action@v2
        with:
          context: ./rust/
          build-args: |
            RUST_VERSION=1.56.1
            IMAGE_NAME=${{ matrix.rust_image_name }}
          pull: true
          push: true
          tags: zimg/rust:1.56.1${{ matrix.suffix }},zimg/rust:1.56${{ matrix.suffix }},zimg/rust:stable${{ matrix.suffix }}

      -
        name: rust-1.58.0
        uses: docker/build-push-action@v2
        with:
          context: ./rust/
          build-args: |
            RUST_VERSION=1.58.0
            IMAGE_NAME=${{ matrix.rust_image_name }}
          pull: true
          push: true
          tags: zimg/rust:1.58.0${{ matrix.suffix }},zimg/rust:1.58${{ matrix.suffix }},zimg/rust:edge${{ matrix.suffix }}
